### ISSUE TITLE
Why are messages assigned to a specific instance?

### ISSUE THREAD

**Issue by SvenAbels** [zone-eu/zmta-webadmin#14]
We are currently using zone-mta with multiple instances on different servers sharing the same MongoDB backend, each of them havign an own instanceId.

We disovered that Emails are assigned to an instanceId. Once an email is assigned to an instanceId it will only be handled by this instance - e.g. in case that it's deferred. 

Why is this the case? Wouldn't it be better if any instance would be able to handle the message when the next delivery is due? This would allow a better load balancing and it would allow another server to deliver the message - e.g. in case that the first one is blocked or down.  -  Why is a message bound to a specific instance?

Or is this necessary for properly handling Greylisting (i.e. do servers always require the same server IP to deliver the same message for passing Greylisting after a while?)?

Best regards,

Sven

**Comment by andris9** [comment]
You're right, once a message gets into deferred state then it needs to be handled by the same server due to greylisting. Some greylist implementations may check for /24, so it may not be an issue but it is safer to always use the same IP.

You should provision multiple IP addresses for each server to handle blocking so ZoneMTA would be able to rotate IP addresses when making delivery attempts. And if a server is down then it only concerns deferred messages assigned to this specific instance - these messages are already delayed due to deferring anyway and adding some time on top of it should not matter.

**Comment by SvenAbels** [comment]
Thanks a lot for the fast reply. 

You wrote

> You should provision multiple IP addresses for each server to handle blocking so ZoneMTA would be able to rotate IP addresses when making delivery attempts. 

Can zone-mta distinguish between blocking and greylisting? Because otherwise, wouldn't the use of multiple IPs mean that different IPs are used again during the greylisting (i.e. the same problem as using multiple servers)?

**Comment by andris9** [comment]
Yes, if ZoneMTA detects that some server has blacklisted an IP then this IP is temporarily removed from the pool (for this specific server only) and deferred messages get a new IP assigned (if available).

**Comment by SvenAbels** [comment]
Great :-)


Just an idea: Wouldn't it be good to also reset the "assigned" to "no" in those situations which would also allow another server (with another IP) to pick up this message?   That would also be great for those servers that have only one IP as they could 'release' the message to other servers.

**Comment by andris9** [comment]
Blacklist handling works best on servers with lots of IP addresses and not so well with servers that have only a single IP. All IP provisioning etc is done at send time and if at that point it turns out the assigned IP is blacklisted then there are no other addresses available to fall back to.

**Comment by SvenAbels** [comment]
OK, thanks a lot for this info. :-)
