### ISSUE TITLE
Webadmin interface failed to start

### ISSUE THREAD

**Issue by w3update** [zone-eu/zmta-webadmin#2]
After copying webadmin interface files.
npm start does not work and give following error.

info Express WWW server listening on port 8082
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1028:11)
    at exports._exceptionWithHostPort (util.js:1051:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)

npm ERR! Linux 3.10.0-514.6.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v7.6.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! zmta-webadmin@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zmta-webadmin@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmta-webadmin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmta-webadmin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmta-webadmin
npm ERR! There is likely additional logging output above.

Any solution?

**Comment by andris9** [comment]
You need Redis to use this application. I found out this was undocumented, so I added the requirements to README [here](https://github.com/zone-eu/zmta-webadmin/blob/master/README.md#requirements)
