### ISSUE TITLE
Where is the log server?

### ISSUE THREAD

**Issue by Dexus** [zone-eu/zmta-webadmin#5]
When i try to look for an queueID i get the error with the data from the log server... that should be listen on port 5388

**Comment by andris9** [comment]
Oh, I don't think I have made the log server public yet. It's nothing too specific, just an UDP listener that serves the stored data via HTTP. I have to clean the code though before releasing it.

**Comment by Etharin** [comment]
Does the log server link into Redis/Mongo? Is there any chance of having a look at the code for it or a way to make the search functionality work otherwise? I've change the http://localhost:5388 to false so it returns nothing found instead of an error but it would be useful to have this working.

**Comment by andris9** [comment]
The logs service is being replaced, for the mean time I put the current code up [here](https://github.com/andris9/zone-logs).

**Comment by Etharin** [comment]
Thanks Andris.
