### ISSUE TITLE
Webadmin Failed

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zmta-webadmin#6]
Hi ,
I don't know about problem please someone help me in this 
I download the package of web admin and paste into were zonemta is runs 
and then i used npm install --production. then i used npm start
then it show this errors
> zmta-webadmin@1.0.0 start /root/download/zone-mta-template/zmta-webadmin
> node server.js

/root/download/zone-mta-template/zmta-webadmin/node_modules/config/lib/config.js:933
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: '/root/download/zone-mta-template/zmta-webadmin/config/default.js': SyntaxError: Unexpected identifier
    at Config.util.parseFile (/root/download/zone-mta-template/zmta-webadmin/node_modules/config/lib/config.js:933:11)
    at /root/download/zone-mta-template/zmta-webadmin/node_modules/config/lib/config.js:702:28
    at Array.forEach (<anonymous>)
    at /root/download/zone-mta-template/zmta-webadmin/node_modules/config/lib/config.js:698:14
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/root/download/zone-mta-template/zmta-webadmin/node_modules/config/lib/config.js:697:13)
    at new Config (/root/download/zone-mta-template/zmta-webadmin/node_modules/config/lib/config.js:122:27)
    at Object.<anonymous> (/root/download/zone-mta-template/zmta-webadmin/node_modules/config/lib/config.js:1767:31)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zmta-webadmin@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmta-webadmin@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by andris9** [comment]
Did you change anything in the config/default.js file?

**Comment by Manishjodhani** [comment]
no

**Comment by andris9** [comment]
Can you try to do this and see if the output is different:

```
$ git clone git://github.com/zone-eu/zmta-webadmin.git
Cloning into 'zmta-webadmin'...
...
$ cd zmta-webadmin/
$ npm install --production
added 178 packages in 6.385s
$ npm start

> zmta-webadmin@1.0.0 start /Users/andris/Desktop/zmta-webadmin
> node server.js

info Express WWW server listening on port 8082
```

**Comment by Manishjodhani** [comment]
same output as your.....then what should i do ???

**Comment by andris9** [comment]
It means it works, the server is listening and can be used.

**Comment by Manishjodhani** [comment]
one more thing.....how can i run this administration page from outside current server
can you tell me??

**Comment by andris9** [comment]
You can run it wherever you want to, it just needs to be able to connect to the correct Redis and ZoneMTA API defined in the config file.

**Comment by martandya** [comment]
not able to run this administration page from outside current server ......
Please suggest that what i need to do ...

Many Thanks ...

**Comment by Manishjodhani** [comment]
have you changed the ports??

**Comment by YosuCadilla** [comment]
@Manishjodhani Please check updated documentation here:
https://github.com/zone-eu/zmta-webadmin (merging is pending)
If merging is not yet done, please check here:
https://github.com/YosuCadilla/zmta-webadmin
