### ISSUE TITLE
Zmta-webadmin pannel not open

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zmta-webadmin#7]
Hi,
I have  connected to my Redis and ZoneMTA API defined in the config file.
But when Point your browser to http://localhost:8082 then this error show

> connect ECONNREFUSED 127.0.0.1:8080

this is zmta-webadmin pannel logs

> nfo HTTP GET / 500 51.725 ms - -
> info HTTP GET /bootstrap/css/bootstrap.min.css 304 3.850 ms - -
> info HTTP GET /moment/zmta.js 304 1.236 ms - -
> info HTTP GET /moment/moment.min.js 304 0.834 ms - -
> info HTTP GET /bootstrap/css/bootstrap-theme.min.css 304 2.091 ms - -
> info HTTP GET /jquery/jquery.min.js 304 1.953 ms - -
> info HTTP GET /bootstrap/js/bootstrap.min.js 304 1.978 ms - -
> info HTTP GET /send 200 23.426 ms - -
> info HTTP GET /bootstrap/css/bootstrap.min.css 304 1.266 ms - -
> info HTTP GET /bootstrap/css/bootstrap-theme.min.css 304 2.041 ms - -
> info HTTP GET /jquery/jquery.min.js 304 2.203 ms - -
> info HTTP GET /bootstrap/js/bootstrap.min.js 304 2.355 ms - -
> info HTTP GET /moment/moment.min.js 304 1.442 ms - -
> info HTTP GET /moment/zmta.js 304 1.439 ms - -
> info HTTP POST /send 500 89.424 ms - -
> info HTTP GET /bootstrap/css/bootstrap.min.css 304 2.806 ms - -
> info HTTP GET /bootstrap/css/bootstrap-theme.min.css 304 2.866 ms - -
> info HTTP GET /jquery/jquery.min.js 304 2.925 ms - -
> info HTTP GET /bootstrap/js/bootstrap.min.js 304 3.009 ms - -
> info HTTP GET /moment/moment.min.js 304 2.944 ms - -
> info HTTP GET /moment/zmta.js 304 3.055 ms 

help me out in this????

**Comment by andris9** [comment]
Check that you have the [correct port number](https://github.com/zone-eu/zone-mta/blob/e1c0df56e1e7971cc53a4f9064373e5456ee1f82/config/default.js#L228)
