### ISSUE TITLE
Invalid response code 404

### ISSUE THREAD

**Issue by Manishjodhani** [zone-eu/zmta-webadmin#8]
Hi,
when i open webadmin pannel it show this error

> > zmta-webadmin@1.0.0 start /root/download/zone-mta-template/zmta-webadmin-master
> > node server.js
> 
> info Express WWW server listening on port 8082
> info HTTP GET /zones 404 10.826 ms - 144
> info HTTP GET /zones 404 2.205 ms - 144
> info HTTP GET /zones 404 1.945 ms - 144
> info HTTP GET /zones 404 1.539 ms - 144
> info HTTP GET /zones 404 1.249 ms - 144
> info HTTP GET / 500 76.988 ms - -
> info HTTP GET /bootstrap/css/bootstrap-theme.min.css 304 7.036 ms - -
> info HTTP GET /bootstrap/css/bootstrap.min.css 304 7.006 ms - -
> info HTTP GET /moment/moment.min.js 304 2.218 ms - -
> info HTTP GET /jquery/jquery.min.js 304 2.536 ms - -
> info HTTP GET /bootstrap/js/bootstrap.min.js 304 2.900 ms - -
> info HTTP GET /moment/zmta.js 304 0.592 ms - -
> info HTTP GET /zones 404 2.638 ms - 144
> info HTTP GET /zones 404 2.172 ms - 144
> info HTTP GET /zones 404 1.820 ms - 144
> info HTTP GET /zones 404 1.545 ms - 144
> info HTTP GET /zones 404 1.197 ms - 144
> info HTTP GET /zones 404 0.793 ms - 144
> info HTTP GET /zones 404 1.110 ms - 144
> info HTTP GET /zones 404 1.285 ms - 144

Please help me out..???????
please

**Comment by andris9** [comment]
it means that [apiServer](https://github.com/zone-eu/zmta-webadmin/blob/master/config/default.js#L14) is not configured properly, it points to some other HTTP server and not to [ZoneMTA API](https://github.com/zone-eu/zone-mta/blob/e1c0df56e1e7971cc53a4f9064373e5456ee1f82/config/default.js#L227-L230)

**Comment by Manishjodhani** [comment]
Please tell me how can i do that.....

**Comment by Manishjodhani** [comment]
when i changed in apiserver and start the npm it show me this

[root@vps166879 zmta-webadmin-master]# npm restart

> zmta-webadmin@1.0.0 start /root/download/zone-mta-template/zmta-webadmin-master
> node server.js

/root/download/zone-mta-template/zmta-webadmin-master/node_modules/config/lib/config.js:946
    throw new Error("Cannot parse config file: '" + fullFilename + "': " + e3);
    ^

Error: Cannot parse config file: '/root/download/zone-mta-template/zmta-webadmin-master/config/default.js': SyntaxError: Invalid or unexpected token
    at Config.util.parseFile (/root/download/zone-mta-template/zmta-webadmin-master/node_modules/config/lib/config.js:946:11)
    at /root/download/zone-mta-template/zmta-webadmin-master/node_modules/config/lib/config.js:715:28
    at Array.forEach (<anonymous>)
    at /root/download/zone-mta-template/zmta-webadmin-master/node_modules/config/lib/config.js:711:14
    at Array.forEach (<anonymous>)
    at Config.util.loadFileConfigs (/root/download/zone-mta-template/zmta-webadmin-master/node_modules/config/lib/config.js:710:13)
    at new Config (/root/download/zone-mta-template/zmta-webadmin-master/node_modules/config/lib/config.js:135:27)
    at Object.<anonymous> (/root/download/zone-mta-template/zmta-webadmin-master/node_modules/config/lib/config.js:1780:31)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zmta-webadmin@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmta-webadmin@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-08T09_11_51_729Z-debug.log

**Comment by Manishjodhani** [comment]
and here is the log file contents 
4 verbose run-script   'restart',
4 verbose run-script   'prestart',
4 verbose run-script   'start',
4 verbose run-script   'poststart',
4 verbose run-script   'postrestart' ]
5 info lifecycle zmta-webadmin@1.0.0~prerestart: zmta-webadmin@1.0.0
6 info lifecycle zmta-webadmin@1.0.0~prestop: zmta-webadmin@1.0.0
7 info lifecycle zmta-webadmin@1.0.0~stop: zmta-webadmin@1.0.0
8 info lifecycle zmta-webadmin@1.0.0~poststop: zmta-webadmin@1.0.0
9 info lifecycle zmta-webadmin@1.0.0~restart: zmta-webadmin@1.0.0
10 info lifecycle zmta-webadmin@1.0.0~prestart: zmta-webadmin@1.0.0
11 info lifecycle zmta-webadmin@1.0.0~start: zmta-webadmin@1.0.0
12 verbose lifecycle zmta-webadmin@1.0.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle zmta-webadmin@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/download/zone-mta-template/zmta-webadmin-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
14 verbose lifecycle zmta-webadmin@1.0.0~start: CWD: /root/download/zone-mta-template/zmta-webadmin-master
15 silly lifecycle zmta-webadmin@1.0.0~start: Args: [ '-c', 'node server.js' ]
16 silly lifecycle zmta-webadmin@1.0.0~start: Returned: code: 1  signal: null
17 info lifecycle zmta-webadmin@1.0.0~start: Failed to exec start script
18 verbose stack Error: zmta-webadmin@1.0.0 start: `node server.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
18 verbose stack     at EventEmitter.emit (events.js:160:13)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:160:13)
18 verbose stack     at maybeClose (internal/child_process.js:943:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
19 verbose pkgid zmta-webadmin@1.0.0
20 verbose cwd /root/download/zone-mta-template/zmta-webadmin-master
21 verbose Linux 3.10.0-693.17.1.el7.x86_64
22 verbose argv "/usr/bin/node" "/usr/bin/npm" "restart"
23 verbose node v9.5.0
24 verbose npm  v5.6.0
25 error code ELIFECYCLE
26 error errno 1
27 error zmta-webadmin@1.0.0 start: `node server.js`
27 error Exit status 1
28 error Failed at the zmta-webadmin@1.0.0 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Manishjodhani** [comment]
Thanks sir
It's running
